"use client";

import React from "react";

export default function ResearchPage() {
  return (
    <div className="flex-1 p-8 bg-[#060814] text-white overflow-y-auto">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">Research: Fundamentals of Flight</h1>
        
        <div className="bg-[#0a0e18] border border-[rgba(255,255,255,0.1)] rounded-xl p-8 mb-8">
          <h2 className="text-xl font-bold mb-4 text-blue-400">The Four Forces of Flight</h2>
          <p className="text-slate-300 mb-4">
            A glider in flight is acted upon by four aerodynamic forces:
          </p>
          <ul className="list-disc list-inside text-slate-400 space-y-2 mb-6 ml-4">
            <li><strong className="text-white">Lift:</strong> The upward force generated by the wings moving through the air.</li>
            <li><strong className="text-white">Weight (Gravity):</strong> The downward force pulling the glider towards the earth.</li>
            <li><strong className="text-white">Thrust:</strong> The forward force. For a glider, initial thrust comes from the launch mechanism.</li>
            <li><strong className="text-white">Drag:</strong> The backward force, or air resistance, opposing the glider&apos;s motion.</li>
          </ul>
        </div>

        <div className="bg-[#0a0e18] border border-[rgba(255,255,255,0.1)] rounded-xl p-8">
          <h2 className="text-xl font-bold mb-4 text-blue-400">Stability</h2>
          <p className="text-slate-300 mb-4">
            For a glider to fly well, it must be stable in three axes:
          </p>
          <ul className="list-disc list-inside text-slate-400 space-y-2 ml-4">
            <li><strong className="text-white">Pitch (Lateral Axis):</strong> Controlled by the Horizontal Stabilizer and the position of the Center of Gravity relative to the Neutral Point.</li>
            <li><strong className="text-white">Roll (Longitudinal Axis):</strong> Governed by the wing&apos;s Dihedral angle.</li>
            <li><strong className="text-white">Yaw (Vertical Axis):</strong> Maintained by the Vertical Stabilizer (tail fin).</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
